apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-management
  namespace: job-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: job-management
  template:
    metadata:
      labels:
        name: job-management
    spec:
      serviceAccountName: job-management
      containers:
        - name: job-management
          # Replace this with the built image name
          image: github.com/vincentpli/job-management/cmd/manager
          command:
          - job-management
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "job-management"
